"""update length password

Revision ID: 0c3f7e5b5b4a
Revises:
Create Date: 2024-01-03 15:24:30.674265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c3f7e5b5b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', existing_type=sa.String(120), type_=sa.String(None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', existing_type=sa.String(None), type_=sa.String(120))
    # ### end Alembic commands ###
